### ISSUE TITLE
Create layouts for landing page and post page

### ISSUE THREAD

**Issue by Greenheart** [paccao/allerthsbageri.se#1]
## Basic structure
- [x] Landing page
- [x] Post

## TODO
- [x] Configure tailwind typography plugin
- [x] Add good default typography styling
- [x] Add outline for other components needed for the layout
